### PR TITLE
Performance optimizations (redux)

### PR DESCRIPTION
**Pull request by lochbika**
**This is a fixed version of PR #41**

This set of commits replaces ifelse statements in a number of functions with explicit attributions through logical indexing. Additionally, the output data frame in the fwi function is pre-allocated now to avoid incremental c statements that concatenate the results in the loop.

This decreases the computation time from 90 seconds to 30 seconds for my test data set, which is a data frame with ~15,000 records.

The tests ran successfully (with one minor modification of test fwi_11)

### CODE REVIEW

**Comment by lochbika** [comment]
Now the branches are set to dev in both repos. I will start the code review of my changes one of these days.

**Review by lochbika — COMMENTED** [review]
I went through the changes and couldn't find any redundancies or otherwise unnecessary code. 
To my best understanding the code runs fine. The build tests pass, as well.

**Comment by BadgerOnABike** [comment]
Looks good to me, I'm wondering if there are ways to further optimize the `if()` as in if there is an in loop variable  we can use instead of recalling `!prec_sel` for instance. For now this is more than fine though and I'll continue to dig around and see what else can continue to be optimized.

Thank you so much for your effort here, this is really helpful!

**Comment by lochbika** [comment]
Excellent, thanks.
I not sure how much the performance increase will be with further optimizing at the moment. I used a profiler to identify the most significant bottlenecks.
But of course, there are definitely more places in the code where a bit more performance can be squeezed out.

**Pull request merged**
